name: Build & push image to repository

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
        env:
          NPM_GITHUB_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
      - run: npm run build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push the docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: getf1tickets/auth-server:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
