name: Build & push image to repository

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: generate-npmrc-docker
        run: |
          echo "always-auth=true" >> .npmrc-docker
          echo "@getf1tickets:registry=https://npm.pkg.github.com/" >> .npmrc-docker
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_GITHUB_TOKEN }}" >> .npmrc-docker
      - name: Build and push the docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ghcr.io/getf1tickets/auth-server
          tags: ${{ github.sha }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
